[mypy]
files = web

strict = true
strict_bytes = true
local_partial_types = true
ignore_missing_imports = true

disable_error_code =
  attr-defined,
  no-untyped-def,
  no-any-return,
  type-arg,
  no-untyped-call