[project]
name = "fastapi-sqlalchemy-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic==1.17.2",
    "bcrypt==5.0.0",
    "dishka==1.7.2",
    "fastapi==0.124.4",
    "loguru==0.7.3",
    "pydantic[email]==2.12.5",
    "pyjwt==2.10.1",
    "python-multipart==0.0.20",
    "sqlalchemy[asyncio]==2.0.45",
    "taskiq==0.12.1",
    "taskiq-redis==1.2.0",
    "uvicorn[standard]==0.38.0",
    "websockets==15.0.1",
    "pytest==9.0.2",
    "botocore>=1.37.3",
    "aiobotocore==3.0.0",
    "psycopg[binary,pool]==3.3.2",
    "pytest-asyncio==1.3.0",
    "redis[hiredis]>=7.0.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mypy>=1.15.0",
    "ruff==0.14.*",
    "testcontainers[postgres,redis]==4.13.3",
]
